### ISSUE TITLE
Web Lineage assignment not working 

### ISSUE THREAD

**Issue by nsekesi** [johnlees/PopPUNK-web#26]
Hello,
I am trying to calculate the genome-genome distance for 81 E. cecorum isolate assemblies on the web program, but it is not working. It ran for over 24 hours and there are still no results. Can anyone help?
Thank you!

**Comment by johnlees** [comment]
Sorry, the web interface is currently unavailable while we develop a second more stable version. Also, for the web version currently only have immediate plans to support _S. pnuemoniae_. There's a warning about this on the documentation, but I will add one to the README of this repo too
